class Book {
  String title;
  double price;
  String cover;
  String author;
  String genre;
  String language;
  String authorImg;
  bool seller;
  String summary;
  String showImage;
  String age;
  double rating;

  Book({
    required this.title,
    required this.price,
    required this.cover,
    required this.author,
    required this.genre,
    required this.language,
    required this.authorImg,
    required this.seller,
    required this.summary,
    required this.showImage,
    required this.age,
    required this.rating,
  });
}

List<Book> bookList = [
  Book(
    title: "To Kill a Mockingbird",
    price: 9.99,
    cover: "https://images.penguinrandomhouse.com/cover/9780061120084",
    author: "Harper Lee",
    genre: "Classic Fiction",
    language: "English",
    authorImg: "https://upload.wikimedia.org/wikipedia/commons/1/15/Harper_Lee_Nov07.jpg",
    seller: true,
    summary: "A novel about the serious issues of rape and racial inequality.",
    showImage: "https://images.penguinrandomhouse.com/cover/9780061120084",
    age: "12+",
    rating: 4.8,
  ),
  Book(
    title: "1984",
    price: 8.49,
    cover: "https://m.media-amazon.com/images/I/41wYbyr3LLL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
    author: "George Orwell",
    genre: "Dystopian Fiction",
    language: "English",
    authorImg: "https://upload.wikimedia.org/wikipedia/commons/c/c3/George_Orwell_press_photo.jpg",
    seller: true,
    summary: "A dystopian social science fiction novel and cautionary tale.",
    showImage: "https://m.media-amazon.com/images/I/41wYbyr3LLL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
    age: "14+",
    rating: 4.7,
  ),
  Book(
    title: "Pride and Prejudice",
    price: 7.99,
    cover: "https://m.media-amazon.com/images/I/51sC5tH9K3L.jpg",
    author: "Jane Austen",
    genre: "Romance",
    language: "English",
    authorImg: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Jane_Austen_coloured_version.jpg",
    seller: true,
    summary: "A romantic novel that also critiques the British landed gentry.",
    showImage: "https://m.media-amazon.com/images/I/51sC5tH9K3L.jpg",
    age: "12+",
    rating: 4.6,
  ),
  Book(
    title: "The Great Gatsby",
    price: 10.49,
    cover: "https://images-na.ssl-images-amazon.com/images/I/81af+MCATTL.jpg",
    author: "F. Scott Fitzgerald",
    genre: "Classic Fiction",
    language: "English",
    authorImg: "https://upload.wikimedia.org/wikipedia/commons/a/a9/F_Scott_Fitzgerald_1921.jpg",
    seller: true,
    summary: "A story about the Jazz Age in the United States.",
    showImage: "https://images-na.ssl-images-amazon.com/images/I/81af+MCATTL.jpg",
    age: "13+",
    rating: 4.7,
  ),
  Book(
    title: "Moby Dick",
    price: 11.50,
    cover: "https://m.media-amazon.com/images/I/41RZ3n9cUfL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
    author: "Herman Melville",
    genre: "Adventure",
    language: "English",
    authorImg: "https://upload.wikimedia.org/wikipedia/commons/6/68/Herman_Melville.jpg",
    seller: true,
    summary: "The voyage of the whaling ship Pequod, led by Captain Ahab.",
    showImage: "https://m.media-amazon.com/images/I/41RZ3n9cUfL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
    age: "14+",
    rating: 4.5,
  ),
  Book(
    title: "War and Peace",
    price: 12.99,
    cover: "https://upload.wikimedia.org/wikipedia/en/thumb/7/74/War-and-peace-book-cover-1952.jpg/220px-War-and-peace-book-cover-1952.jpg",
    author: "Leo Tolstoy",
    genre: "Historical Fiction",
    language: "Russian",
    authorImg: "https://upload.wikimedia.org/wikipedia/commons/7/70/L.N.Tolstoy_Prokudin-Gorsky.jpg",
    seller: true,
    summary: "A novel chronicling the history of the French invasion of Russia.",
    showImage: "https://upload.wikimedia.org/wikipedia/en/thumb/7/74/War-and-peace-book-cover-1952.jpg/220px-War-and-peace-book-cover-1952.jpg",
    age: "15+",
    rating: 4.8,
  ),
  Book(
    title: "The Catcher in the Rye",
    price: 9.99,
    cover: "https://m.media-amazon.com/images/I/71h-CTcKJgL.jpg",
    author: "J.D. Salinger",
    genre: "Classic Fiction",
    language: "English",
    authorImg: "https://upload.wikimedia.org/wikipedia/commons/7/79/JD_Salinger.jpg",
    seller: true,
    summary: "The experiences of a young boy, Holden Caulfield, in New York.",
    showImage: "https://m.media-amazon.com/images/I/71h-CTcKJgL.jpg",
    age: "13+",
    rating: 4.5,
  ),
  Book(
    title: "The Hobbit",
    price: 14.99,
    cover: "https://m.media-amazon.com/images/I/51KtCkOHhEL._SX331_BO1,204,203,200_.jpg",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    language: "English",
    authorImg: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Tolkien_1916.jpg",
    seller: true,
    summary: "The journey of Bilbo Baggins as he aids a group of dwarves.",
    showImage: "https://m.media-amazon.com/images/I/51KtCkOHhEL._SX331_BO1,204,203,200_.jpg",
    age: "10+",
    rating: 4.9,
  ),
  Book(
    title: "The Alchemist",
    price: 12.99,
    cover: "https://m.media-amazon.com/images/I/41Xrmx6HQqL.jpg",
    author: "Paulo Coelho",
    genre: "Adventure",
    language: "Portuguese",
    authorImg: "https://upload.wikimedia.org/wikipedia/commons/2/27/Paulo_Coelho_Frankfurt_2007.jpg",
    seller: true,
    summary: "A novel about the journey of a young shepherd in search of treasure.",
    showImage: "https://m.media-amazon.com/images/I/41Xrmx6HQqL.jpg",
    age: "12+",
    rating: 4.6,
  ),
  Book(
    title: "The Picture of Dorian Gray",
    price: 7.99,
    cover: "https://m.media-amazon.com/images/I/71KnMND6PpL.jpg",
    author: "Oscar Wilde",
    genre: "Philosophical Fiction",
    language: "English",
    authorImg: "https://upload.wikimedia.org/wikipedia/commons/9/91/Oscar_Wilde_portrait.jpg",
    seller: true,
    summary: "A novel about the downfall of a man who remains young while his portrait ages.",
    showImage: "https://m.media-amazon.com/images/I/71KnMND6PpL.jpg",
    age: "14+",
    rating: 4.7,
  ),
  // Add 40 more books following the same structure
];

